import Boundary from './Boundary';
import {lazy,Suspense,useEffect,useMemo,useState} from 'react';
import {cap,Observation,soundscape,sources} from '../shared/domain';
import {Alert,timeLabel} from './ui';
import {loadSnapshot,loadNote} from './data';
const CampusMap=lazy(()=>import('./Map'));
export default function Explore({view}:{view:string}){
 const [kind,setKind]=useState('real'),[source,setSource]=useState('all'),[time,setTime]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[records,setRecords]=useState<Observation[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,reload]=useState(0),[layer,setLayer]=useState<'disturbance'|'nature'>('disturbance'),[selected,select]=useState(''),[expanded,expand]=useState(false),[loadedAt,setLoadedAt]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');loadSnapshot(controller.signal).then(s=>{setRecords(s.records.filter(r=>r.kind===kind));setLoadedAt(s.updated_at||'');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[kind,revision]);
 const rows=useMemo(()=>records.filter(r=>{const hour=(new Date(r.observed_at).getUTCHours()+8)%24,day=new Date(Date.parse(r.observed_at)+8*3600000).toISOString().slice(0,10);return (source==='all'||r.source===source)&&(!from||day>=from)&&(!to||day<=to)&&(time==='all'||(time==='morning'?hour>=6&&hour<12:time==='afternoon'?hour>=12&&hour<18:hour>=18||hour<6));}),[records,source,time,from,to]);
 const areas=useMemo(()=>soundscape(rows,layer),[rows,layer]),sound=view==='soundscape',list=view==='list';
 const area=areas.find(p=>p.id===selected)||areas[0],record=rows.find(p=>p.id===selected)||rows[0];
 const markers=sound?areas.map(p=>({id:p.id,lat:p.latitude,lon:p.longitude,label:`${p.name}: ${p.numerator} of ${p.denominator} notes`,text:p.denominator>=3?`${p.percent}%`:p.denominator?'Few':'—',ratio:p.denominator>=3?p.numerator/p.denominator:null,color:layer==='nature'?'#245b49':'#a65315',count:`${p.numerator}/${p.denominator}`})):rows.map(r=>({id:r.id,lat:r.public_latitude,lon:r.public_longitude,label:`${r.place_name}: ${r.disturbance}/5 disturbance`,text:String(r.disturbance)}));
 const clear=()=>{setSource('all');setTime('all');setFrom('');setTo('');};
 return <><div className="explore-heading"><p className="eyebrow">Explore / Kent Ridge</p><h1>{sound?'Find your next pause.':'Listen through the notes.'}</h1></div><nav className="segmented" aria-label="Explore views">{[['Map','map'],['List','list'],['Soundscape','soundscape']].map(([t,v])=><a key={v} href={'#/explore/'+v} className={view===v?'selected':''} aria-current={view===v?'page':undefined}>{t}</a>)}</nav>
 {sound&&<div className="layer-switch"><button className={layer==='disturbance'?'selected disturbance':''} aria-pressed={layer==='disturbance'} onClick={()=>setLayer('disturbance')}>Stronger disturbance</button><button className={layer==='nature'?'selected natural':''} aria-pressed={layer==='nature'} onClick={()=>setLayer('nature')}>Natural sounds</button></div>}
 <div className="compact-filters"><label className="filter-label">Data<select value={kind} onChange={e=>setKind(e.target.value)}>{[['real','Real notes'],['hypothetical','Hypothetical']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label className="filter-label">Source<select value={source} onChange={e=>setSource(e.target.value)}><option value="all">All sources</option>{sources.map(s=><option key={s} value={s}>{cap(s)}</option>)}</select></label><label className="filter-label">Time<select value={time} onChange={e=>setTime(e.target.value)}><option value="all">All times</option><option value="morning">06–12 SGT</option><option value="afternoon">12–18 SGT</option><option value="night">18–06 SGT</option></select></label></div><details className="date-filter"><summary>Date range / refresh</summary><div className="coordinate-fields"><label className="field">From<input className="input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field">Through<input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><button className="textlink plain" onClick={()=>reload(n=>n+1)}>Refresh map data</button></details>
 {loading?<p className="inline-note section" role="status">Loading observations…</p>:error?<><Alert>{error}</Alert><button className="button secondary" onClick={()=>reload(n=>n+1)}>Try again</button></>:<><p className="count-label small" role="status">{rows.length} / {records.length} published {kind} notes match · SGT</p>{kind!=='real'&&<p className="inline-note warn">Hypothetical observations</p>}
 {rows.length===0?<section className="empty">{!list&&<Boundary map><Suspense fallback={<p>Loading map…</p>}><CampusMap/></Suspense></Boundary>}<h2 className="section">No matching observations.</h2><p className="lead">{records.length===0?'The next map update will appear here.':'Try another source or time range.'}</p><button className="button secondary section" onClick={clear}>Clear filters</button><a className="textlink" href="#/observe">Contribute a minute of listening →</a></section>:<>
 {sound&&<p className="layer-caption">{layer==='nature'?'Share hearing clear or dominant natural sounds':'Share rating disturbance 4 or 5 out of 5'}</p>}
 {list?<div className="record-list">{rows.map(r=><a className="record" href={'#/note/'+r.id} key={r.id}><div className="row between"><span className={'tag '+r.source}>{cap(r.source)}</span><span className="small">{r.disturbance}/5 disturbance</span></div><h2>{r.place_name}</h2><p className="small">{timeLabel(r.observed_at)} · {r.kind} →</p></a>)}</div>:<div className="explore-layout"><div className="map-column"><Boundary map><Suspense fallback={<p>Loading map…</p>}><CampusMap pins={markers} selected={sound?area?.id:record?.id} onSelect={select}/></Suspense></Boundary>{sound?<div className="layer-legend"><span>0%</span><span className={'ramp '+(layer==='nature'?'green':'orange')}/><span>100%</span><span className="small">Few: fewer than 3</span></div>:<p className="small section-sm">Numbers: subjective disturbance, 1–5.</p>}<p className="small evidence">Approximate 100 m positions · {kind} notes<br/>{sound?'Equal-size circles show proportions.':'Select a point or use List for keyboard-friendly browsing.'}</p></div><aside className="detail-panel"><button className="panel-toggle" onClick={()=>expand(!expanded)} aria-expanded={expanded} aria-controls="place-extra"><span><span className="eyebrow">{sound?'Area insight':'Selected observation'}</span><strong>{sound?area?.name:record?.place_name}</strong></span><span className="panel-chevron">{expanded?'−':'+'}</span></button>{sound&&area?<div className="insight-row"><strong className="insight-number">{area.denominator>=3?area.percent+'%':area.denominator?'Few notes':'No data'}</strong><span>{area.numerator} of {area.denominator} {layer==='nature'?'rated':'total'} notes<br/><span className="small">{layer==='nature'?'Clear / dominant nature':'Disturbance rated 4–5'}</span></span></div>:record&&<p className="small">{cap(record.source)} · {record.disturbance}/5<br/>{timeLabel(record.observed_at)}</p>}<div id="place-extra" className={'panel-reveal '+(expanded?'is-open':'')} inert={!expanded}><div><p className="small section-sm">{sound&&area?`${area.total} total notes; ${area.total-area.denominator} excluded from this denominator. Fewer than 3 valid notes: no colour.`:record?.note||'No note added.'}</p><a className="textlink" href={sound?'#/method':'#/note/'+record?.id}>{sound?'How to read these patterns':'Read this observation'} →</a></div></div></aside></div>}
 </>}<p className="small section-sm">{loadedAt?`Updated ${timeLabel(loadedAt)}.`:"No observations published yet."} Map updated periodically.</p><a className="textlink" href="#/story">What could these notes help us find? →</a></>}
 </>;
}
export function Note({id}:{id:string}){const [r,setR]=useState<Observation|null>(null),[error,setError]=useState('');useEffect(()=>{let live=true;setR(null);setError('');loadNote(id).then(d=>{if(live)setR(d);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[id]);return <><a href="#/explore/list" className="textlink">← Back to observations</a>{error?<Alert>{error}</Alert>:r?<><p className="eyebrow section">{r.kind} observation</p><h1>{r.place_name}</h1><p className="small section-sm">{timeLabel(r.observed_at)}</p><div className="metrics section"><strong className="metric-number">{r.disturbance}/5</strong><div>{cap(r.source)}<p className="small">While {r.activity}</p></div></div><p className="section">{r.note||'No note added.'}</p><p className="small section">Natural sounds: {r.nature_presence||'Not answered'}.<br/>Reference: {r.id}</p><a className="textlink" href="#/privacy">Privacy & your data →</a></>:<p>Loading observation…</p>}</>;}
