import Boundary from './Boundary';
import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ratings} from '../shared/domain';
import {Botanical,Header,Nav,Reveal} from './ui';
import ObservationForm from './Form';
import './base.css';import './theme.css';import './app.css';
const Explore=lazy(()=>import('./Explore')),Note=lazy(()=>import('./Explore').then(m=>({default:m.Note})));
let homeSeen=false;
function useRoute(){const [route,setRoute]=useState(location.hash.slice(1)||'/');useEffect(()=>{const f=()=>setRoute(location.hash.slice(1)||'/');addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f);},[]);return route;}
function Home(){const animate=useRef(!homeSeen);useEffect(()=>{homeSeen=true;},[]);return <div className={animate.current?'home-grid':'home-grid home-revisited'}><div className="home-intro"><p className="eyebrow enter">NUS Kent Ridge / A listening project</p><h1 className="hero enter">A little pause.<br/>A different<br/><em>perspective.</em></h1><p className="lead enter">Listen to the campus around you.<br/>Help make room for a better break.</p></div><figure className="hero-art enter"><Botanical/></figure><div className="home-links"><a className="button secondary" href="#/explore/soundscape">Explore the soundscape ↗</a><a className="textlink" href="#/story">Why we listen <span>→</span></a></div></div>;}
function Story(){return <><div className="story-opening"><p className="eyebrow">Why we listen</p><h1 className="hero">Make room<br/>for a <em>better<br/>pause.</em></h1><p className="lead">Every place has a soundscape.<br/>Together, we can learn to listen.</p><Botanical/></div><Reveal id="story1" className="story-chapter"><p className="chapter-number">01 / CHOOSE YOUR MOMENT</p><h2>A little less<br/>disruption.</h2><p>Where could you read, talk or simply rest? Look at when and where people felt disturbed, then choose a place to try.</p></Reveal><Reveal id="story2" className="story-chapter dark"><p className="chapter-number">02 / LISTEN AGAIN</p><h2>A starting point<br/>for change.</h2><p>Help campus stewards find places with repeated reports of disruption. Patterns can guide a return visit, a conversation or a sound measurement.</p><div className="story-orbits" aria-hidden="true"><i/><i/><i/></div></Reveal><Reveal id="story3" className="story-chapter"><p className="chapter-number">03 / FIND A NATURAL PAUSE</p><h2>Closer to leaves.<br/>Closer to birdsong.</h2><p>Find notes where natural sounds were clearly heard. Explore somewhere to pause with rustling leaves, water or birds around you.</p><Botanical/></Reveal><Reveal id="story4" className="story-ending"><p className="eyebrow">A shared perspective</p><h2>Small observations.<br/>More thoughtful places.</h2><p className="lead">Start with the notes. Stay curious about what you hear.</p></Reveal></>;}
function Guide(){return <><p className="eyebrow">Your field guide</p><h1>One minute.<br/>Your perspective.</h1><p className="lead">Record what you experience, from a safe public place.</p>{[['Stop and listen','Pause for about 60 seconds. Stay clear of roads, work sites and restricted areas.'],['Choose your place and time','At your listening spot, tap Use my location to add coordinates, or use a public place preset. Select the place name and enter the observation date and time in SGT.'],['Describe what you heard','Choose the main sound, disturbance level and your activity.'],['Add a little context','Natural sounds, weather and a short note are optional. Leave out personal details.'],['Submit your observation','Submit the Qualtrics form and wait for its confirmation. The map is updated periodically.']].map(([t,d],i)=><div className="instruction" key={t}><span className="number">{i+1}</span><div><h2>{t}</h2><p>{d}</p></div></div>)}<h2 className="section">The disturbance scale</h2>{ratings.map((r,i)=><div className="scale-row" key={i}><span className="number">{i+1}</span><p>{r}</p></div>)}<a className="textlink" href="#/privacy">Privacy & your data →</a><a className="button section" href="#/observe">Start an observation →</a></>;}
function Privacy(){return <><p className="eyebrow">Privacy & your data</p><h1>What happens<br/>to your note?</h1><h2 className="section">Your submission</h2><p className="section-sm">The observation form stores responses in Qualtrics. It asks about a public place, time, sounds and your activity. Use my location is optional: after you allow it, the form records your coordinates, location accuracy and capture time. You can remove these before continuing. No names, student numbers, photos or recordings are requested.</p><h2 className="section">On the map</h2><p className="section-sm">The project lead exports responses, checks the entries and removes personal details before updating the map. Public notes include approximate locations, observation times, ratings and relevant context.</p><h2 className="section">Updates</h2><p className="section-sm">The map is updated periodically. Its update date shows which version you are viewing.</p><a className="textlink" href="#/guide">Back to the guide →</a></>;}
function Method(){return <><p className="eyebrow">About the map</p><h1>How to read<br/>the soundscape.</h1><h2 className="section">Stronger disturbance</h2><p className="section-sm">Number of notes rated 4 or 5, divided by all notes in the same approximate 100 m area and current filters.</p><h2 className="section">Natural sounds</h2><p className="section-sm">Clear or dominant natural-sound answers, divided by all valid nature answers in the same area and filters. Missing and Unsure are excluded, never treated as zero.</p><h2 className="section">Symbols and sample size</h2><p className="section-sm">Equal-size circles show the proportion of matching observations. Fewer than 3 valid notes: an uncoloured, dashed circle. No valid notes: —, not 0%.</p><h2 className="section">Compare like with like</h2><p className="section-sm">Filter by source, date and time. Real and hypothetical observations are shown separately. Counts refer to notes, not individual participants.</p><a className="textlink" href="#/explore/soundscape">Back to Soundscape →</a></>;}
function App(){const route=useRoute(),path=route.split('?')[0],step=path.split('/')[2]||'map',form=path==='/observe'||path.startsWith('/observe/'),explore=path.startsWith('/explore'),home=path==='/';useEffect(()=>{const h=document.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}document.querySelector('main')?.scrollTo(0,0);document.title=(form?'Share an observation':explore?'Explore':'Campus Sound Notes')+' · Campus Sound Notes';},[route]);
return <div className={'phone live-app '+(explore?'explore-shell':'')} data-page={home?'01-home':path==='/story'?'27-story':explore?'07-explore-map':form?'survey':'live'}><Header/><main className="content step-enter"><Suspense fallback={<p role="status">Loading…</p>}>{home?<Home/>:form?<ObservationForm/>:explore?<Explore view={['map','list','soundscape'].includes(step)?step:'map'}/>:path.startsWith('/note/')?<Note id={step}/>:path==='/story'?<Story/>:path==='/guide'?<Guide/>:path==='/privacy'?<Privacy/>:path==='/method'?<Method/>:<><h1>Page not found.</h1><a className="textlink" href="#/">Return home →</a></>}</Suspense></main>{home?<div className="dock"><a className="button" href="#/observe">Start an observation →</a></div>:path==='/story'?<div className="dock"><a className="button" href="#/explore/soundscape">Explore the soundscape →</a></div>:<Nav/>}</div>;}
createRoot(document.getElementById('root')!).render(<Boundary><App/></Boundary>);
