import {useEffect,useRef,useState} from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
type Pin={id:string;lat:number;lon:number;label:string;text:string;color?:string;ratio?:number|null;count?:string};
export default function CampusMap({pins=[],selected,onSelect,onPosition,position}:{pins?:Pin[];selected?:string;onSelect?:(id:string)=>void;onPosition?:(lat:number,lon:number)=>void;position?:[number,number]}){
 const holder=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),layer=useRef<L.LayerGroup|null>(null),onPos=useRef(onPosition),onSel=useRef(onSelect);onPos.current=onPosition;onSel.current=onSelect;
 const [failed,setFailed]=useState(false);
 useEffect(()=>{const m=L.map(holder.current!,{scrollWheelZoom:false,minZoom:13,maxZoom:19}).setView([1.299,103.775],15);map.current=m;const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(m);tiles.on('tileerror',()=>setFailed(true));layer.current=L.layerGroup().addTo(m);m.on('click',e=>onPos.current?.(e.latlng.lat,e.latlng.lng));const resize=new ResizeObserver(()=>m.invalidateSize());resize.observe(holder.current!);return()=>{resize.disconnect();m.remove();};},[]);
 useEffect(()=>{if(!layer.current)return;layer.current.clearLayers();for(const p of pins){const el=document.createElement('button');el.type='button';el.className='geo-marker '+(p.id===selected?'is-selected':'')+(p.ratio===null?' sparse':'');el.setAttribute('aria-label',p.label);const disc=document.createElement('span');disc.textContent=p.text;disc.className='geo-disc';if(p.color){disc.style.borderColor=p.color;disc.style.background=p.ratio===null?'#fffef9':`color-mix(in srgb, ${p.color} ${(p.ratio??.3)*65}%, #fffef9)`;}el.append(disc);if(p.count){const count=document.createElement('span');count.className='geo-count';count.textContent=p.count;el.append(count);}el.onclick=(e)=>{e.stopPropagation();onSel.current?.(p.id);};const marker=L.marker([p.lat,p.lon],{icon:L.divIcon({html:el,className:'geo-icon',iconSize:[76,88],iconAnchor:[38,38]}),keyboard:false}).addTo(layer.current);const tooltip=document.createElement('span');tooltip.textContent=p.label;marker.bindTooltip(tooltip,{direction:'top'});}},[pins,selected]);
 useEffect(()=>{if(!map.current||!position)return;const marker=L.circleMarker(position,{radius:10,color:'#245B49',fillColor:'#fff',fillOpacity:1,weight:4}).addTo(map.current);map.current.panTo(position,{animate:!matchMedia('(prefers-reduced-motion:reduce)').matches});return()=>{marker.remove();};},[position?.[0],position?.[1]]);
 return <div><div className="live-map" ref={holder} role="region" aria-label={onPosition?'Choose an observation location on the map':'Map of reviewed observations'}/>{failed&&<p className="inline-note warn" role="status">Map tiles could not load. {onPosition?'Enter coordinates below or use a place preset.':'Use List to read all observations.'}</p>}{onPosition&&<p className="small section-sm">Tap to place a pin, or enter coordinates below.</p>}</div>;
}
